name = "Materials Factory"
power = 2
rate = 25

[[build_costs]]
material = "BasicMaterials"
cost = 200

[[inputs]]
material = "Salvage"
value = 20

[[outputs]]
material = "ConstructionMaterials"
value = 1

[[upgrades]]
name = "Oil Reformer"
power = 1
rate = 150
inputs = [
    { material = "Oil", value = 120 },
    { material = "Water", value = 30 }
]
outputs = [
    { material = "Petrol", value = 150 }
]
build_costs = [
    { material = "ConstructionMaterials", cost = 200 }
]