name = "Materials Factory"
power = 2
rate = 25

[[build_costs]]
material = "BasicMaterials"
cost = 200

[[inputs]]
material = "Salvage"
value = 20

[[outputs]]
material = "ConstructionMaterials"
value = 1