[default_upgrade]
name = "Materials Factory"
build_costs = [
    { material = "BasicMaterials", cost = 200 }
]

[[default_upgrade.production_channels]]
power = 2
rate = 25
inputs = [
    { material = "Salvage", value = 10 }
]
outputs = [
    { material = "ConstructionMaterials", value = 1 }
]

# FIXME: Upgrades here need to have multiple routes
[upgrades."Metal Press"]
name = "Metal Press"
build_costs = [
    { material = "ConstructionMaterials", cost = 25 }
]
parent = "Materials Factory"

[[upgrades."Metal Press".production_channels]]
power = 4
rate = 25
inputs = [
    { material = "Salvage", value = 15 },
    { material = "Petrol", value = 25 }
]
outputs = [
    { material = "ConstructionMaterials", value = 3 }
]

[upgrades."Smelter"]
name = "Smelter"
build_costs = [
    { material = "ConstructionMaterials", cost = 25 }
]
parent = "Materials Factory"

[[upgrades."Smelter".production_channels]]
power = 4
rate = 25
inputs = [
    { material = "Salvage", value = 15 },
    { material = "Coke", value = 25 }
]
outputs = [
    { material = "ConstructionMaterials", value = 3 }
]

[upgrades."Forge"]
name = "Forge"
build_costs = [
    { material = "ConstructionMaterials", cost = 200 }
]
parent = "Materials Factory"

[[upgrades."Forge".production_channels]]
power = 2
rate = 60
inputs = [
    { material = "Salvage", value = 15 },
    { material = "Coke", value = 75 }
]
outputs = [
    { material = "AssemblyMaterialsI", value = 1 }
]

[[upgrades."Forge".production_channels]]
power = 2
rate = 60
inputs = [
    { material = "Salvage", value = 15 },
    { material = "Petrol", value = 50 }
]
outputs = [
    { material = "AssemblyMaterialsII", value = 1 }
]

[upgrades."Assembly Bay"]
name = "Assembly Bay"
build_costs = [
    { material = "BasicMaterials", cost = 50 }
]
parent = "Materials Factory"

[[upgrades."Assembly Bay".production_channels]]
power = 2
rate = 25
inputs = [
    { material = "Salvage", value = 25 },
]
outputs = [
    { material = "ConstructionMaterials", value = 1 },
    { material = "SandBag", value = 5 }
]

[[upgrades."Assembly Bay".production_channels]]
power = 2
rate = 25
inputs = [
    { material = "Salvage", value = 25 },
]
outputs = [
    { material = "ConstructionMaterials", value = 1 },
    { material = "BarbedWire", value = 5 }
]