[workspace]

members = [
    "foxhole-production-calculator",
    "foxhole-production-calculator-types",
    "foxhole-production-calculator-cli",
    "foxhole-production-calculator-frontend",
]

[profile.release]
lto = true
panic = "abort"
codegen-units = 1
