name = "Ammunition Factory"
power = 4

[[build_costs]]
material = "ConstructionMaterials"
cost = 25

[[inputs]]
material = "ConstructionMaterials"
value = 1

[[inputs]]
material = "HeavyExplosiveMaterials"
value = 1

[[outputs]]
material = "Napalm"
value = 1