name = "MetalWorks Factory"
power = 5

[[build_costs]]
material = "ConstructionMaterials"
cost = 125

[[inputs]]
material = "ConstructionMaterials"
value = 3

[[inputs]]
material = "Components"
value = 20

[[outputs]]
material = "ProcessedConstructionMaterials"
value = 1